// Mocks generated by Mockito 5.1.0 from annotations
// in shopify_manager/test/infrastructure/product/barcode_scanner/flutter_barcode_scanner_facade_impl_test.dart.
// Do not manually edit this file.

import 'package:flutter_barcode_scanner/flutter_barcode_scanner.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [FlutterBarcodeScanner].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterBarcodeScanner extends _i1.Mock
    implements _i2.FlutterBarcodeScanner {
  MockFlutterBarcodeScanner() {
    _i1.throwOnMissingStub(this);
  }
}
