// Mocks generated by Mockito 5.0.16 from annotations
// in shopify_client/test/infrastracture/shopping/firebase_shop_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i9;
import 'dart:typed_data' as _i11;

import 'package:cloud_firestore/cloud_firestore.dart' as _i5;
import 'package:firebase_core/firebase_core.dart' as _i6;
import 'package:firebase_storage/firebase_storage.dart' as _i7;
import 'package:geoflutterfire/src/collection/default.dart' as _i2;
import 'package:geoflutterfire/src/collection/with_converter.dart' as _i3;
import 'package:geoflutterfire/src/geoflutterfire.dart' as _i8;
import 'package:geoflutterfire/src/models/distance_doc_snapshot.dart' as _i10;
import 'package:geoflutterfire/src/models/point.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGeoFireCollectionRef_0 extends _i1.Fake
    implements _i2.GeoFireCollectionRef {}

class _FakeGeoFireCollectionWithConverterRef_1<T> extends _i1.Fake
    implements _i3.GeoFireCollectionWithConverterRef<T> {}

class _FakeGeoFirePoint_2 extends _i1.Fake implements _i4.GeoFirePoint {}

class _FakeDocumentReference_3<T extends Object?> extends _i1.Fake
    implements _i5.DocumentReference<T> {}

class _FakeFirebaseApp_4 extends _i1.Fake implements _i6.FirebaseApp {}

class _FakeDuration_5 extends _i1.Fake implements Duration {}

class _FakeReference_6 extends _i1.Fake implements _i7.Reference {}

class _FakeFirebaseFirestore_7 extends _i1.Fake
    implements _i5.FirebaseFirestore {}

class _FakeCollectionReference_8<T extends Object?> extends _i1.Fake
    implements _i5.CollectionReference<T> {}

class _FakeQuery_9<T extends Object?> extends _i1.Fake implements _i5.Query<T> {
}

class _FakeQuerySnapshot_10<T extends Object?> extends _i1.Fake
    implements _i5.QuerySnapshot<T> {}

class _FakeSettings_11 extends _i1.Fake implements _i5.Settings {}

class _FakeWriteBatch_12 extends _i1.Fake implements _i5.WriteBatch {}

class _FakeLoadBundleTask_13 extends _i1.Fake implements _i5.LoadBundleTask {}

/// A class which mocks [Geoflutterfire].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeoflutterfire extends _i1.Mock implements _i8.Geoflutterfire {
  MockGeoflutterfire() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GeoFireCollectionRef collection(
          {_i5.Query<Map<String, dynamic>>? collectionRef}) =>
      (super.noSuchMethod(
          Invocation.method(#collection, [], {#collectionRef: collectionRef}),
          returnValue:
              _FakeGeoFireCollectionRef_0()) as _i2.GeoFireCollectionRef);
  @override
  _i3.GeoFireCollectionWithConverterRef<T> collectionWithConverter<T>(
          {_i5.Query<T>? collectionRef}) =>
      (super.noSuchMethod(
              Invocation.method(#collectionWithConverter, [],
                  {#collectionRef: collectionRef}),
              returnValue: _FakeGeoFireCollectionWithConverterRef_1<T>())
          as _i3.GeoFireCollectionWithConverterRef<T>);
  @override
  _i2.GeoFireCollectionRef customCollection(
          {_i5.Query<Map<String, dynamic>>? collectionRef}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #customCollection, [], {#collectionRef: collectionRef}),
              returnValue: _FakeGeoFireCollectionRef_0())
          as _i2.GeoFireCollectionRef);
  @override
  _i4.GeoFirePoint point({double? latitude, double? longitude}) =>
      (super.noSuchMethod(
          Invocation.method(
              #point, [], {#latitude: latitude, #longitude: longitude}),
          returnValue: _FakeGeoFirePoint_2()) as _i4.GeoFirePoint);
  @override
  String toString() => super.toString();
}

/// A class which mocks [GeoFireCollectionRef].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeoFireCollectionRef extends _i1.Mock
    implements _i2.GeoFireCollectionRef {
  MockGeoFireCollectionRef() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Stream<List<_i5.DocumentSnapshot<Map<String, dynamic>>>> within(
          {_i4.GeoFirePoint? center,
          double? radius,
          String? field,
          bool? strictMode}) =>
      (super.noSuchMethod(
              Invocation.method(#within, [], {
                #center: center,
                #radius: radius,
                #field: field,
                #strictMode: strictMode
              }),
              returnValue: Stream<
                  List<_i5.DocumentSnapshot<Map<String, dynamic>>>>.empty())
          as _i9.Stream<List<_i5.DocumentSnapshot<Map<String, dynamic>>>>);
  @override
  _i9.Stream<List<_i10.DistanceDocSnapshot<Map<String, dynamic>>>> withinWithDistance(
          {_i4.GeoFirePoint? center,
          double? radius,
          String? field,
          bool? strictMode}) =>
      (super.noSuchMethod(
              Invocation.method(#withinWithDistance, [], {
                #center: center,
                #radius: radius,
                #field: field,
                #strictMode: strictMode
              }),
              returnValue: Stream<
                  List<_i10.DistanceDocSnapshot<Map<String, dynamic>>>>.empty())
          as _i9.Stream<List<_i10.DistanceDocSnapshot<Map<String, dynamic>>>>);
  @override
  _i9.Stream<List<_i5.DocumentSnapshot<Map<String, dynamic>>>> data(
          String? id) =>
      (super.noSuchMethod(Invocation.method(#data, [id]),
              returnValue: Stream<
                  List<_i5.DocumentSnapshot<Map<String, dynamic>>>>.empty())
          as _i9.Stream<List<_i5.DocumentSnapshot<Map<String, dynamic>>>>);
  @override
  _i9.Future<_i5.DocumentReference<Map<String, dynamic>>> add(
          Map<String, dynamic>? data) =>
      (super.noSuchMethod(Invocation.method(#add, [data]),
              returnValue:
                  Future<_i5.DocumentReference<Map<String, dynamic>>>.value(
                      _FakeDocumentReference_3<Map<String, dynamic>>()))
          as _i9.Future<_i5.DocumentReference<Map<String, dynamic>>>);
  @override
  _i9.Future<void> delete(dynamic id) =>
      (super.noSuchMethod(Invocation.method(#delete, [id]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> setDoc(String? id, Object? data, {bool? merge = false}) =>
      (super.noSuchMethod(
          Invocation.method(#setDoc, [id, data], {#merge: merge}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> setPoint(
          String? id, String? field, double? latitude, double? longitude) =>
      (super.noSuchMethod(
          Invocation.method(#setPoint, [id, field, latitude, longitude]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Stream<List<_i5.DocumentSnapshot<Map<String, dynamic>>>> protectedWithin(
          {_i4.GeoFirePoint? center,
          double? radius,
          String? field,
          _i5.GeoPoint? Function(Map<String, dynamic>)? geopointFrom,
          bool? strictMode}) =>
      (super.noSuchMethod(
              Invocation.method(#protectedWithin, [], {
                #center: center,
                #radius: radius,
                #field: field,
                #geopointFrom: geopointFrom,
                #strictMode: strictMode
              }),
              returnValue: Stream<
                  List<_i5.DocumentSnapshot<Map<String, dynamic>>>>.empty())
          as _i9.Stream<List<_i5.DocumentSnapshot<Map<String, dynamic>>>>);
  @override
  _i9.Stream<List<_i10.DistanceDocSnapshot<Map<String, dynamic>>>>
      protectedWithinWithDistance(
              {_i4.GeoFirePoint? center,
              double? radius,
              String? field,
              _i5.GeoPoint? Function(Map<String, dynamic>)? geopointFrom,
              bool? strictMode}) =>
          (super.noSuchMethod(
              Invocation.method(#protectedWithinWithDistance, [], {
                #center: center,
                #radius: radius,
                #field: field,
                #geopointFrom: geopointFrom,
                #strictMode: strictMode
              }),
              returnValue: Stream<
                  List<
                      _i10.DistanceDocSnapshot<
                          Map<String, dynamic>>>>.empty()) as _i9
              .Stream<List<_i10.DistanceDocSnapshot<Map<String, dynamic>>>>);
  @override
  _i9.Stream<
      List<_i5.QueryDocumentSnapshot<Map<String, dynamic>>>> mergeObservable(
          Iterable<_i9.Stream<List<_i5.QueryDocumentSnapshot<Map<String, dynamic>>>>>?
              queries) =>
      (super.noSuchMethod(Invocation.method(#mergeObservable, [queries]),
              returnValue: Stream<
                  List<_i5.QueryDocumentSnapshot<Map<String, dynamic>>>>.empty())
          as _i9.Stream<List<_i5.QueryDocumentSnapshot<Map<String, dynamic>>>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [FirebaseStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseStorage extends _i1.Mock implements _i7.FirebaseStorage {
  MockFirebaseStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.FirebaseApp get app => (super.noSuchMethod(Invocation.getter(#app),
      returnValue: _FakeFirebaseApp_4()) as _i6.FirebaseApp);
  @override
  set app(_i6.FirebaseApp? _app) =>
      super.noSuchMethod(Invocation.setter(#app, _app),
          returnValueForMissingStub: null);
  @override
  String get bucket =>
      (super.noSuchMethod(Invocation.getter(#bucket), returnValue: '')
          as String);
  @override
  set bucket(String? _bucket) =>
      super.noSuchMethod(Invocation.setter(#bucket, _bucket),
          returnValueForMissingStub: null);
  @override
  Duration get maxOperationRetryTime =>
      (super.noSuchMethod(Invocation.getter(#maxOperationRetryTime),
          returnValue: _FakeDuration_5()) as Duration);
  @override
  Duration get maxUploadRetryTime =>
      (super.noSuchMethod(Invocation.getter(#maxUploadRetryTime),
          returnValue: _FakeDuration_5()) as Duration);
  @override
  Duration get maxDownloadRetryTime =>
      (super.noSuchMethod(Invocation.getter(#maxDownloadRetryTime),
          returnValue: _FakeDuration_5()) as Duration);
  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(Invocation.getter(#pluginConstants),
          returnValue: <dynamic, dynamic>{}) as Map<dynamic, dynamic>);
  @override
  _i7.Reference ref([String? path]) =>
      (super.noSuchMethod(Invocation.method(#ref, [path]),
          returnValue: _FakeReference_6()) as _i7.Reference);
  @override
  _i7.Reference refFromURL(String? url) =>
      (super.noSuchMethod(Invocation.method(#refFromURL, [url]),
          returnValue: _FakeReference_6()) as _i7.Reference);
  @override
  void setMaxOperationRetryTime(Duration? time) =>
      super.noSuchMethod(Invocation.method(#setMaxOperationRetryTime, [time]),
          returnValueForMissingStub: null);
  @override
  void setMaxUploadRetryTime(Duration? time) =>
      super.noSuchMethod(Invocation.method(#setMaxUploadRetryTime, [time]),
          returnValueForMissingStub: null);
  @override
  void setMaxDownloadRetryTime(Duration? time) =>
      super.noSuchMethod(Invocation.method(#setMaxDownloadRetryTime, [time]),
          returnValueForMissingStub: null);
  @override
  _i9.Future<void> useEmulator({String? host, int? port}) =>
      (super.noSuchMethod(
          Invocation.method(#useEmulator, [], {#host: host, #port: port}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> useStorageEmulator(String? host, int? port) =>
      (super.noSuchMethod(Invocation.method(#useStorageEmulator, [host, port]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [CollectionReference].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockCollectionReference<T extends Object?> extends _i1.Mock
    implements _i5.CollectionReference<T> {
  MockCollectionReference() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(Invocation.getter(#id), returnValue: '') as String);
  @override
  String get path =>
      (super.noSuchMethod(Invocation.getter(#path), returnValue: '') as String);
  @override
  _i5.FirebaseFirestore get firestore =>
      (super.noSuchMethod(Invocation.getter(#firestore),
          returnValue: _FakeFirebaseFirestore_7()) as _i5.FirebaseFirestore);
  @override
  Map<String, dynamic> get parameters =>
      (super.noSuchMethod(Invocation.getter(#parameters),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
  @override
  _i9.Future<_i5.DocumentReference<T>> add(T? data) =>
      (super.noSuchMethod(Invocation.method(#add, [data]),
              returnValue: Future<_i5.DocumentReference<T>>.value(
                  _FakeDocumentReference_3<T>()))
          as _i9.Future<_i5.DocumentReference<T>>);
  @override
  _i5.DocumentReference<T> doc([String? path]) => (super.noSuchMethod(
      Invocation.method(#doc, [path]),
      returnValue: _FakeDocumentReference_3<T>()) as _i5.DocumentReference<T>);
  @override
  _i5.CollectionReference<R> withConverter<R extends Object?>(
          {_i5.FromFirestore<R>? fromFirestore,
          _i5.ToFirestore<R>? toFirestore}) =>
      (super.noSuchMethod(
              Invocation.method(#withConverter, [],
                  {#fromFirestore: fromFirestore, #toFirestore: toFirestore}),
              returnValue: _FakeCollectionReference_8<R>())
          as _i5.CollectionReference<R>);
  @override
  String toString() => super.toString();
  @override
  _i5.Query<T> endAtDocument(_i5.DocumentSnapshot<Object?>? documentSnapshot) =>
      (super.noSuchMethod(Invocation.method(#endAtDocument, [documentSnapshot]),
          returnValue: _FakeQuery_9<T>()) as _i5.Query<T>);
  @override
  _i5.Query<T> endAt(List<Object?>? values) =>
      (super.noSuchMethod(Invocation.method(#endAt, [values]),
          returnValue: _FakeQuery_9<T>()) as _i5.Query<T>);
  @override
  _i5.Query<T> endBeforeDocument(
          _i5.DocumentSnapshot<Object?>? documentSnapshot) =>
      (super.noSuchMethod(
          Invocation.method(#endBeforeDocument, [documentSnapshot]),
          returnValue: _FakeQuery_9<T>()) as _i5.Query<T>);
  @override
  _i5.Query<T> endBefore(List<Object?>? values) =>
      (super.noSuchMethod(Invocation.method(#endBefore, [values]),
          returnValue: _FakeQuery_9<T>()) as _i5.Query<T>);
  @override
  _i9.Future<_i5.QuerySnapshot<T>> get([_i5.GetOptions? options]) =>
      (super.noSuchMethod(Invocation.method(#get, [options]),
          returnValue: Future<_i5.QuerySnapshot<T>>.value(
              _FakeQuerySnapshot_10<T>())) as _i9.Future<_i5.QuerySnapshot<T>>);
  @override
  _i5.Query<T> limit(int? limit) =>
      (super.noSuchMethod(Invocation.method(#limit, [limit]),
          returnValue: _FakeQuery_9<T>()) as _i5.Query<T>);
  @override
  _i5.Query<T> limitToLast(int? limit) =>
      (super.noSuchMethod(Invocation.method(#limitToLast, [limit]),
          returnValue: _FakeQuery_9<T>()) as _i5.Query<T>);
  @override
  _i9.Stream<_i5.QuerySnapshot<T>> snapshots(
          {bool? includeMetadataChanges = false}) =>
      (super.noSuchMethod(
              Invocation.method(#snapshots, [],
                  {#includeMetadataChanges: includeMetadataChanges}),
              returnValue: Stream<_i5.QuerySnapshot<T>>.empty())
          as _i9.Stream<_i5.QuerySnapshot<T>>);
  @override
  _i5.Query<T> orderBy(Object? field, {bool? descending = false}) =>
      (super.noSuchMethod(
          Invocation.method(#orderBy, [field], {#descending: descending}),
          returnValue: _FakeQuery_9<T>()) as _i5.Query<T>);
  @override
  _i5.Query<T> startAfterDocument(
          _i5.DocumentSnapshot<Object?>? documentSnapshot) =>
      (super.noSuchMethod(
          Invocation.method(#startAfterDocument, [documentSnapshot]),
          returnValue: _FakeQuery_9<T>()) as _i5.Query<T>);
  @override
  _i5.Query<T> startAfter(List<Object?>? values) =>
      (super.noSuchMethod(Invocation.method(#startAfter, [values]),
          returnValue: _FakeQuery_9<T>()) as _i5.Query<T>);
  @override
  _i5.Query<T> startAtDocument(
          _i5.DocumentSnapshot<Object?>? documentSnapshot) =>
      (super.noSuchMethod(
          Invocation.method(#startAtDocument, [documentSnapshot]),
          returnValue: _FakeQuery_9<T>()) as _i5.Query<T>);
  @override
  _i5.Query<T> startAt(List<Object?>? values) =>
      (super.noSuchMethod(Invocation.method(#startAt, [values]),
          returnValue: _FakeQuery_9<T>()) as _i5.Query<T>);
  @override
  _i5.Query<T> where(Object? field,
          {Object? isEqualTo,
          Object? isNotEqualTo,
          Object? isLessThan,
          Object? isLessThanOrEqualTo,
          Object? isGreaterThan,
          Object? isGreaterThanOrEqualTo,
          Object? arrayContains,
          List<Object?>? arrayContainsAny,
          List<Object?>? whereIn,
          List<Object?>? whereNotIn,
          bool? isNull}) =>
      (super.noSuchMethod(
          Invocation.method(#where, [
            field
          ], {
            #isEqualTo: isEqualTo,
            #isNotEqualTo: isNotEqualTo,
            #isLessThan: isLessThan,
            #isLessThanOrEqualTo: isLessThanOrEqualTo,
            #isGreaterThan: isGreaterThan,
            #isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
            #arrayContains: arrayContains,
            #arrayContainsAny: arrayContainsAny,
            #whereIn: whereIn,
            #whereNotIn: whereNotIn,
            #isNull: isNull
          }),
          returnValue: _FakeQuery_9<T>()) as _i5.Query<T>);
}

/// A class which mocks [FirebaseFirestore].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseFirestore extends _i1.Mock implements _i5.FirebaseFirestore {
  MockFirebaseFirestore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.FirebaseApp get app => (super.noSuchMethod(Invocation.getter(#app),
      returnValue: _FakeFirebaseApp_4()) as _i6.FirebaseApp);
  @override
  set app(_i6.FirebaseApp? _app) =>
      super.noSuchMethod(Invocation.setter(#app, _app),
          returnValueForMissingStub: null);
  @override
  set settings(_i5.Settings? settings) =>
      super.noSuchMethod(Invocation.setter(#settings, settings),
          returnValueForMissingStub: null);
  @override
  _i5.Settings get settings => (super.noSuchMethod(Invocation.getter(#settings),
      returnValue: _FakeSettings_11()) as _i5.Settings);
  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(Invocation.getter(#pluginConstants),
          returnValue: <dynamic, dynamic>{}) as Map<dynamic, dynamic>);
  @override
  _i5.CollectionReference<Map<String, dynamic>> collection(
          String? collectionPath) =>
      (super.noSuchMethod(Invocation.method(#collection, [collectionPath]),
              returnValue: _FakeCollectionReference_8<Map<String, dynamic>>())
          as _i5.CollectionReference<Map<String, dynamic>>);
  @override
  _i5.WriteBatch batch() => (super.noSuchMethod(Invocation.method(#batch, []),
      returnValue: _FakeWriteBatch_12()) as _i5.WriteBatch);
  @override
  _i9.Future<void> clearPersistence() =>
      (super.noSuchMethod(Invocation.method(#clearPersistence, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> enablePersistence(
          [_i5.PersistenceSettings? persistenceSettings]) =>
      (super.noSuchMethod(
          Invocation.method(#enablePersistence, [persistenceSettings]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i5.LoadBundleTask loadBundle(_i11.Uint8List? bundle) =>
      (super.noSuchMethod(Invocation.method(#loadBundle, [bundle]),
          returnValue: _FakeLoadBundleTask_13()) as _i5.LoadBundleTask);
  @override
  void useFirestoreEmulator(String? host, int? port,
          {bool? sslEnabled = false}) =>
      super.noSuchMethod(
          Invocation.method(
              #useFirestoreEmulator, [host, port], {#sslEnabled: sslEnabled}),
          returnValueForMissingStub: null);
  @override
  _i9.Future<_i5.QuerySnapshot<Map<String, dynamic>>> namedQueryGet(
          String? name,
          {_i5.GetOptions? options = const _i5.GetOptions()}) =>
      (super.noSuchMethod(
          Invocation.method(#namedQueryGet, [name], {#options: options}),
          returnValue: Future<_i5.QuerySnapshot<Map<String, dynamic>>>.value(
              _FakeQuerySnapshot_10<Map<String, dynamic>>())) as _i9
          .Future<_i5.QuerySnapshot<Map<String, dynamic>>>);
  @override
  _i5.Query<Map<String, dynamic>> collectionGroup(String? collectionPath) =>
      (super.noSuchMethod(Invocation.method(#collectionGroup, [collectionPath]),
              returnValue: _FakeQuery_9<Map<String, dynamic>>())
          as _i5.Query<Map<String, dynamic>>);
  @override
  _i9.Future<void> disableNetwork() =>
      (super.noSuchMethod(Invocation.method(#disableNetwork, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i5.DocumentReference<Map<String, dynamic>> doc(String? documentPath) =>
      (super.noSuchMethod(Invocation.method(#doc, [documentPath]),
              returnValue: _FakeDocumentReference_3<Map<String, dynamic>>())
          as _i5.DocumentReference<Map<String, dynamic>>);
  @override
  _i9.Future<void> enableNetwork() =>
      (super.noSuchMethod(Invocation.method(#enableNetwork, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Stream<void> snapshotsInSync() =>
      (super.noSuchMethod(Invocation.method(#snapshotsInSync, []),
          returnValue: Stream<void>.empty()) as _i9.Stream<void>);
  @override
  _i9.Future<T> runTransaction<T>(_i5.TransactionHandler<T>? transactionHandler,
          {Duration? timeout = const Duration(seconds: 30)}) =>
      (super.noSuchMethod(
          Invocation.method(
              #runTransaction, [transactionHandler], {#timeout: timeout}),
          returnValue: Future<T>.value(null)) as _i9.Future<T>);
  @override
  _i9.Future<void> terminate() =>
      (super.noSuchMethod(Invocation.method(#terminate, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> waitForPendingWrites() =>
      (super.noSuchMethod(Invocation.method(#waitForPendingWrites, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  String toString() => super.toString();
}
