// Mocks generated by Mockito 5.2.0 from annotations
// in shopify_client/test/application/location/location_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shopify_client/domain/core/i_location_facade.dart' as _i3;
import 'package:shopify_domain/core.dart' as _i5;
import 'package:shopify_domain/core/network/network_info.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [ILocationFacade].
///
/// See the documentation for Mockito's code generation for more information.
class MockILocationFacade extends _i1.Mock implements _i3.ILocationFacade {
  MockILocationFacade() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.LocationFailure, _i5.Location>>
      getCurrentLocation() => (super.noSuchMethod(
              Invocation.method(#getCurrentLocation, []),
              returnValue:
                  Future<_i2.Either<_i5.LocationFailure, _i5.Location>>.value(
                      _FakeEither_0<_i5.LocationFailure, _i5.Location>()))
          as _i4.Future<_i2.Either<_i5.LocationFailure, _i5.Location>>);
  @override
  _i4.Future<_i2.Either<_i5.LocationFailure, _i5.Location>>
      getLocationFromString(String? input) => (super.noSuchMethod(
              Invocation.method(#getLocationFromString, [input]),
              returnValue:
                  Future<_i2.Either<_i5.LocationFailure, _i5.Location>>.value(
                      _FakeEither_0<_i5.LocationFailure, _i5.Location>()))
          as _i4.Future<_i2.Either<_i5.LocationFailure, _i5.Location>>);
  @override
  _i4.Future<_i2.Either<_i5.LocationFailure, _i5.Location>> getUserLocation() =>
      (super.noSuchMethod(Invocation.method(#getUserLocation, []),
              returnValue:
                  Future<_i2.Either<_i5.LocationFailure, _i5.Location>>.value(
                      _FakeEither_0<_i5.LocationFailure, _i5.Location>()))
          as _i4.Future<_i2.Either<_i5.LocationFailure, _i5.Location>>);
  @override
  _i4.Future<_i2.Either<_i5.LocationFailure, _i2.Unit>> setUserAddress(
          _i5.Address? address) =>
      (super.noSuchMethod(Invocation.method(#setUserAddress, [address]),
          returnValue: Future<_i2.Either<_i5.LocationFailure, _i2.Unit>>.value(
              _FakeEither_0<_i5.LocationFailure, _i2.Unit>())) as _i4
          .Future<_i2.Either<_i5.LocationFailure, _i2.Unit>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
}
