// Mocks generated by Mockito 5.0.17 from annotations
// in shopify_manager/test/application/shopping/shop_form/shop_form_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:kt_dart/kt.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shopify_manager/domain/shopping/i_shop_repository.dart' as _i3;
import 'package:shopify_manager/domain/shopping/shop.dart' as _i7;
import 'package:shopify_manager/domain/shopping/shop_failure.dart' as _i5;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [IShopRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIShopRepository extends _i1.Mock implements _i3.IShopRepository {
  MockIShopRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.Either<_i5.ShopFailure, _i6.KtList<_i7.Shop>>> watchAll() =>
      (super.noSuchMethod(Invocation.method(#watchAll, []),
              returnValue: Stream<
                  _i2.Either<_i5.ShopFailure, _i6.KtList<_i7.Shop>>>.empty())
          as _i4.Stream<_i2.Either<_i5.ShopFailure, _i6.KtList<_i7.Shop>>>);
  @override
  _i4.Stream<_i2.Either<_i5.ShopFailure, _i6.KtList<_i7.Shop>>> watchNearby() =>
      (super.noSuchMethod(Invocation.method(#watchNearby, []),
              returnValue: Stream<
                  _i2.Either<_i5.ShopFailure, _i6.KtList<_i7.Shop>>>.empty())
          as _i4.Stream<_i2.Either<_i5.ShopFailure, _i6.KtList<_i7.Shop>>>);
  @override
  _i4.Future<_i2.Either<_i5.ShopFailure, _i2.Unit>> create(_i7.Shop? shop) =>
      (super.noSuchMethod(Invocation.method(#create, [shop]),
              returnValue: Future<_i2.Either<_i5.ShopFailure, _i2.Unit>>.value(
                  _FakeEither_0<_i5.ShopFailure, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i5.ShopFailure, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i5.ShopFailure, _i2.Unit>> update(_i7.Shop? shop) =>
      (super.noSuchMethod(Invocation.method(#update, [shop]),
              returnValue: Future<_i2.Either<_i5.ShopFailure, _i2.Unit>>.value(
                  _FakeEither_0<_i5.ShopFailure, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i5.ShopFailure, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i5.ShopFailure, _i2.Unit>> delete(_i7.Shop? shop) =>
      (super.noSuchMethod(Invocation.method(#delete, [shop]),
              returnValue: Future<_i2.Either<_i5.ShopFailure, _i2.Unit>>.value(
                  _FakeEither_0<_i5.ShopFailure, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i5.ShopFailure, _i2.Unit>>);
}
