// Mocks generated by Mockito 5.0.16 from annotations
// in shopify_client/test/application/shop_watcher_bloc/shop_watcher_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:dartz/dartz.dart' as _i4;
import 'package:kt_dart/kt.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shopify_client/domain/core/location.dart' as _i8;
import 'package:shopify_client/domain/shopping/i_shop_repository.dart' as _i2;
import 'package:shopify_client/domain/shopping/shop.dart' as _i7;
import 'package:shopify_client/domain/shopping/shop_failure.dart' as _i5;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [IShopRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIShopRepository extends _i1.Mock implements _i2.IShopRepository {
  MockIShopRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.Either<_i5.ShopFailure, _i6.KtList<_i7.Shop>>> watchNearby(
          _i8.Location? location, double? radius) =>
      (super.noSuchMethod(Invocation.method(#watchNearby, [location, radius]),
              returnValue: Stream<
                  _i4.Either<_i5.ShopFailure, _i6.KtList<_i7.Shop>>>.empty())
          as _i3.Stream<_i4.Either<_i5.ShopFailure, _i6.KtList<_i7.Shop>>>);
  @override
  String toString() => super.toString();
}
