// Mocks generated by Mockito 5.0.17 from annotations
// in shopify_manager/test/application/shopping/shop_logo_picker/shop_logo_picker_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shopify_manager/domain/core/images/image_failure.dart' as _i5;
import 'package:shopify_manager/domain/core/images/photo.dart' as _i6;
import 'package:shopify_manager/infrastructure/core/images/image_picker_image_facade.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [ImagePickerImageFacade].
///
/// See the documentation for Mockito's code generation for more information.
class MockImagePickerImageFacade extends _i1.Mock
    implements _i3.ImagePickerImageFacade {
  MockImagePickerImageFacade() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.ImageFailure, _i6.ShopLogo>> getShopLogo() =>
      (super.noSuchMethod(Invocation.method(#getShopLogo, []),
          returnValue: Future<_i2.Either<_i5.ImageFailure, _i6.ShopLogo>>.value(
              _FakeEither_0<_i5.ImageFailure, _i6.ShopLogo>())) as _i4
          .Future<_i2.Either<_i5.ImageFailure, _i6.ShopLogo>>);
}
