name: shopify_presentation
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage: null

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  dartz: ^0.10.1
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_signin_button: ^2.0.0
  font_awesome_flutter: ^9.0.0
  freezed: ^2.0.3+1
  get_it: ^7.2.0
  kt_dart: ^0.10.0
  loading_overlay: ^0.3.0
  material_floating_search_bar: ^0.3.7
  mobile_scanner: ^1.1.1
  mocktail: ^0.3.0
  path_provider: ^2.0.10
  progress_indicators: ^1.0.0
  responsive_framework: ^0.2.0
  scrollable_positioned_list: ^0.3.2
  shopify_domain:
    path: ../shopify_domain

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.3
  sealed_annotations: ^1.13.0

uses-material-design: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  assets:
    - images/corner_shape.png
    - images/undraw_gone_shopping.png
    - images/logo.png
    - images/test/test_logo.jpg
    - images/test/too_small_logo.jpg
    - images/test/too_big_logo.jpg
    - images/categories/bio.png
    - images/categories/fruits.png
    - images/categories/vegetables.png
    - images/categories/meat.png
    - images/categories/fishAndSeafood.png
    - images/categories/coldCuts.png
    - images/categories/dairy.png
    - images/categories/bread.png
    - images/categories/cakes.png
    - images/categories/fatsAndOils.png
    - images/categories/frozenProducts.png
    - images/categories/coffeeTea.png
    - images/categories/sweets.png
    - images/categories/drinkables.png
    - images/categories/pastaRiceGroats.png
    - images/categories/jamsAndHoney.png
    - images/categories/flourSugarSalt.png
    - images/categories/spices.png
    - images/categories/sauces.png
    - images/categories/saltySnacks.png
    - images/categories/baking.png
    - images/categories/readyMeals.png
    - images/categories/cannedFood.png
    - images/categories/forKids.png
    - images/categories/forPets.png
    - images/categories/cleaningChemicals.png
    - images/categories/cosmetics.png
    - images/categories/beers.png
    - images/categories/wines.png
    - images/categories/otherAlcohols.png
    - images/categories/store.png
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
