// Mocks generated by Mockito 5.2.0 from annotations
// in shopify_manager/test/application/product/product_form/product_form_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:kt_dart/kt.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shopify_domain/auth.dart' as _i6;
import 'package:shopify_domain/core.dart' as _i12;
import 'package:shopify_domain/core/network/network_info.dart' as _i3;
import 'package:shopify_domain/product.dart' as _i8;
import 'package:shopify_domain/shop.dart' as _i9;
import 'package:shopify_manager/domain/auth/i_auth_facade.dart' as _i5;
import 'package:shopify_manager/domain/core/images/i_image_facade.dart' as _i13;
import 'package:shopify_manager/domain/product/i_product_repository.dart'
    as _i7;
import 'package:shopify_manager/domain/shop/i_shop_repository.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeOption_0<A> extends _i1.Fake implements _i2.Option<A> {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i3.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
}

/// A class which mocks [IAuthFacade].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthFacade extends _i1.Mock implements _i5.IAuthFacade {
  MockIAuthFacade() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Option<_i6.ShopifyUser>> getSignedInUser() =>
      (super.noSuchMethod(Invocation.method(#getSignedInUser, []),
              returnValue: Future<_i2.Option<_i6.ShopifyUser>>.value(
                  _FakeOption_0<_i6.ShopifyUser>()))
          as _i4.Future<_i2.Option<_i6.ShopifyUser>>);
  @override
  _i4.Future<_i2.Either<_i6.AuthFailure, _i2.Unit>>
      registerWithEmailAndPassword(
              {_i6.EmailAddress? emailAddress, _i6.Password? password}) =>
          (super.noSuchMethod(
              Invocation.method(#registerWithEmailAndPassword, [],
                  {#emailAddress: emailAddress, #password: password}),
              returnValue: Future<_i2.Either<_i6.AuthFailure, _i2.Unit>>.value(
                  _FakeEither_1<_i6.AuthFailure, _i2.Unit>())) as _i4
              .Future<_i2.Either<_i6.AuthFailure, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i6.AuthFailure, _i2.Unit>> signInWithEmailAndPassword(
          {_i6.EmailAddress? emailAddress, _i6.Password? password}) =>
      (super.noSuchMethod(
              Invocation.method(#signInWithEmailAndPassword, [],
                  {#emailAddress: emailAddress, #password: password}),
              returnValue: Future<_i2.Either<_i6.AuthFailure, _i2.Unit>>.value(
                  _FakeEither_1<_i6.AuthFailure, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i6.AuthFailure, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i6.AuthFailure, _i2.Unit>> signInWithGoogle() =>
      (super.noSuchMethod(Invocation.method(#signInWithGoogle, []),
              returnValue: Future<_i2.Either<_i6.AuthFailure, _i2.Unit>>.value(
                  _FakeEither_1<_i6.AuthFailure, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i6.AuthFailure, _i2.Unit>>);
  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(Invocation.method(#signOut, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
}

/// A class which mocks [IProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIProductRepository extends _i1.Mock
    implements _i7.IProductRepository {
  MockIProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i8.ProductFailure, _i8.Product>> getByBarcode(
          _i8.Barcode? barcode) =>
      (super.noSuchMethod(Invocation.method(#getByBarcode, [barcode]),
              returnValue:
                  Future<_i2.Either<_i8.ProductFailure, _i8.Product>>.value(
                      _FakeEither_1<_i8.ProductFailure, _i8.Product>()))
          as _i4.Future<_i2.Either<_i8.ProductFailure, _i8.Product>>);
  @override
  _i4.Future<_i2.Either<_i8.ProductFailure, _i8.Product>> getFromShopByBarcode(
          _i9.Shop? shop, _i8.Barcode? barcode) =>
      (super.noSuchMethod(
              Invocation.method(#getFromShopByBarcode, [shop, barcode]),
              returnValue:
                  Future<_i2.Either<_i8.ProductFailure, _i8.Product>>.value(
                      _FakeEither_1<_i8.ProductFailure, _i8.Product>()))
          as _i4.Future<_i2.Either<_i8.ProductFailure, _i8.Product>>);
  @override
  _i4.Future<_i2.Either<_i8.ProductFailure, _i2.Unit>> create(
          _i8.ProductForm? productForm) =>
      (super.noSuchMethod(Invocation.method(#create, [productForm]),
          returnValue: Future<_i2.Either<_i8.ProductFailure, _i2.Unit>>.value(
              _FakeEither_1<_i8.ProductFailure, _i2.Unit>())) as _i4
          .Future<_i2.Either<_i8.ProductFailure, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i8.ProductFailure, _i2.Unit>> addToShop(
          _i8.ProductForm? productForm, _i9.Shop? shop, _i8.Price? price) =>
      (super.noSuchMethod(
          Invocation.method(#addToShop, [productForm, shop, price]),
          returnValue: Future<_i2.Either<_i8.ProductFailure, _i2.Unit>>.value(
              _FakeEither_1<_i8.ProductFailure, _i2.Unit>())) as _i4
          .Future<_i2.Either<_i8.ProductFailure, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i8.ProductFailure, _i2.Unit>> update(
          _i8.Product? product) =>
      (super.noSuchMethod(Invocation.method(#update, [product]),
          returnValue: Future<_i2.Either<_i8.ProductFailure, _i2.Unit>>.value(
              _FakeEither_1<_i8.ProductFailure, _i2.Unit>())) as _i4
          .Future<_i2.Either<_i8.ProductFailure, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i8.ProductFailure, _i2.Unit>> delete(
          _i8.Product? product) =>
      (super.noSuchMethod(Invocation.method(#delete, [product]),
          returnValue: Future<_i2.Either<_i8.ProductFailure, _i2.Unit>>.value(
              _FakeEither_1<_i8.ProductFailure, _i2.Unit>())) as _i4
          .Future<_i2.Either<_i8.ProductFailure, _i2.Unit>>);
}

/// A class which mocks [IShopRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIShopRepository extends _i1.Mock implements _i10.IShopRepository {
  MockIShopRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.Either<_i9.ShopFailure, _i11.KtList<_i9.Shop>>> watchAll() =>
      (super.noSuchMethod(Invocation.method(#watchAll, []),
              returnValue: Stream<
                  _i2.Either<_i9.ShopFailure, _i11.KtList<_i9.Shop>>>.empty())
          as _i4.Stream<_i2.Either<_i9.ShopFailure, _i11.KtList<_i9.Shop>>>);
  @override
  _i4.Stream<_i2.Either<_i9.ShopFailure, _i11.KtList<_i9.Shop>>>
      watchNearby() => (super.noSuchMethod(Invocation.method(#watchNearby, []),
              returnValue: Stream<
                  _i2.Either<_i9.ShopFailure, _i11.KtList<_i9.Shop>>>.empty())
          as _i4.Stream<_i2.Either<_i9.ShopFailure, _i11.KtList<_i9.Shop>>>);
  @override
  _i4.Stream<_i2.Either<_i9.ShopFailure, _i11.KtList<_i9.Shop>>>
      watchYourShops() => (super.noSuchMethod(
              Invocation.method(#watchYourShops, []),
              returnValue: Stream<
                  _i2.Either<_i9.ShopFailure, _i11.KtList<_i9.Shop>>>.empty())
          as _i4.Stream<_i2.Either<_i9.ShopFailure, _i11.KtList<_i9.Shop>>>);
  @override
  _i4.Future<_i2.Either<_i9.ShopFailure, _i2.Unit>> create(
          _i9.Shop? shop, _i12.ShopLogo? logo, _i6.ShopifyUser? user) =>
      (super.noSuchMethod(Invocation.method(#create, [shop, logo, user]),
              returnValue: Future<_i2.Either<_i9.ShopFailure, _i2.Unit>>.value(
                  _FakeEither_1<_i9.ShopFailure, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i9.ShopFailure, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i9.ShopFailure, _i2.Unit>> update(_i9.Shop? shop) =>
      (super.noSuchMethod(Invocation.method(#update, [shop]),
              returnValue: Future<_i2.Either<_i9.ShopFailure, _i2.Unit>>.value(
                  _FakeEither_1<_i9.ShopFailure, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i9.ShopFailure, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i9.ShopFailure, _i2.Unit>> delete(_i9.Shop? shop) =>
      (super.noSuchMethod(Invocation.method(#delete, [shop]),
              returnValue: Future<_i2.Either<_i9.ShopFailure, _i2.Unit>>.value(
                  _FakeEither_1<_i9.ShopFailure, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i9.ShopFailure, _i2.Unit>>);
}

/// A class which mocks [IImageFacade].
///
/// See the documentation for Mockito's code generation for more information.
class MockIImageFacade extends _i1.Mock implements _i13.IImageFacade {
  MockIImageFacade() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i12.ImageFailure, _i12.Photo>> getPhoto(
          {int? minHeight = 100,
          int? minWidth = 100,
          int? maxHeight = 1000,
          int? maxWidth = 1000}) =>
      (super.noSuchMethod(
          Invocation.method(#getPhoto, [], {
            #minHeight: minHeight,
            #minWidth: minWidth,
            #maxHeight: maxHeight,
            #maxWidth: maxWidth
          }),
          returnValue: Future<_i2.Either<_i12.ImageFailure, _i12.Photo>>.value(
              _FakeEither_1<_i12.ImageFailure, _i12.Photo>())) as _i4
          .Future<_i2.Either<_i12.ImageFailure, _i12.Photo>>);
  @override
  _i4.Future<
      _i2.Either<_i12.ImageFailure, _i11.KtList<_i12.Photo>>> getMultiplePhotos(
          {int? min = 1,
          int? max = 5,
          int? minHeight = 100,
          int? minWidth = 100,
          int? maxHeight = 1000,
          int? maxWidth = 1000}) =>
      (super.noSuchMethod(
          Invocation.method(#getMultiplePhotos, [], {
            #min: min,
            #max: max,
            #minHeight: minHeight,
            #minWidth: minWidth,
            #maxHeight: maxHeight,
            #maxWidth: maxWidth
          }),
          returnValue: Future<
                  _i2.Either<_i12.ImageFailure, _i11.KtList<_i12.Photo>>>.value(
              _FakeEither_1<_i12.ImageFailure, _i11.KtList<_i12.Photo>>())) as _i4
          .Future<_i2.Either<_i12.ImageFailure, _i11.KtList<_i12.Photo>>>);
}
