// Mocks generated by Mockito 5.2.0 from annotations
// in shopify_client/test/application/cart_and_favourite/cart_and_favourite_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shopify_client/domain/cart/I_cart_facade.dart' as _i3;
import 'package:shopify_domain/cart/cart_failure.dart' as _i5;
import 'package:shopify_domain/core/value_objects.dart' as _i7;
import 'package:shopify_domain/product/product_snippets.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [ICartFacade].
///
/// See the documentation for Mockito's code generation for more information.
class MockICartFacade extends _i1.Mock implements _i3.ICartFacade {
  MockICartFacade() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.CartFailure, _i2.Unit>> addProductToCart(
          _i6.PricedProduct? product,
          {int? quantity = 1}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #addProductToCart, [product], {#quantity: quantity}),
              returnValue: Future<_i2.Either<_i5.CartFailure, _i2.Unit>>.value(
                  _FakeEither_0<_i5.CartFailure, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i5.CartFailure, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i5.CartFailure, _i2.Unit>> addProductToFavourites(
          _i7.UniqueId? id) =>
      (super.noSuchMethod(Invocation.method(#addProductToFavourites, [id]),
              returnValue: Future<_i2.Either<_i5.CartFailure, _i2.Unit>>.value(
                  _FakeEither_0<_i5.CartFailure, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i5.CartFailure, _i2.Unit>>);
}
