// Mocks generated by Mockito 5.2.0 from annotations
// in shopify_client/test/infrastructure/auth/auth_facade_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shopify_domain/auth/auth_failure.dart' as _i7;
import 'package:shopify_domain/auth/shopify_auth.dart' as _i5;
import 'package:shopify_domain/auth/user.dart' as _i4;
import 'package:shopify_domain/auth/value_objects.dart' as _i8;
import 'package:shopify_domain/core/value_objects.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeOption_0<A> extends _i1.Fake implements _i2.Option<A> {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

class _FakeUniqueId_2 extends _i1.Fake implements _i3.UniqueId {}

class _Fake$ShopifyUserCopyWith_3<$Res> extends _i1.Fake
    implements _i4.$ShopifyUserCopyWith<$Res> {}

/// A class which mocks [ShopifyAuth].
///
/// See the documentation for Mockito's code generation for more information.
class MockShopifyAuth extends _i1.Mock implements _i5.ShopifyAuth {
  MockShopifyAuth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Option<_i4.ShopifyUser>> getSignedInUser() =>
      (super.noSuchMethod(Invocation.method(#getSignedInUser, []),
              returnValue: Future<_i2.Option<_i4.ShopifyUser>>.value(
                  _FakeOption_0<_i4.ShopifyUser>()))
          as _i6.Future<_i2.Option<_i4.ShopifyUser>>);
  @override
  _i6.Future<_i2.Either<_i7.AuthFailure, _i2.Unit>>
      registerWithEmailAndPassword(
              {_i8.EmailAddress? emailAddress, _i8.Password? password}) =>
          (super.noSuchMethod(
              Invocation.method(#registerWithEmailAndPassword, [],
                  {#emailAddress: emailAddress, #password: password}),
              returnValue: Future<_i2.Either<_i7.AuthFailure, _i2.Unit>>.value(
                  _FakeEither_1<_i7.AuthFailure, _i2.Unit>())) as _i6
              .Future<_i2.Either<_i7.AuthFailure, _i2.Unit>>);
  @override
  _i6.Future<_i2.Either<_i7.AuthFailure, _i2.Unit>> signInWithEmailAndPassword(
          {_i8.EmailAddress? emailAddress, _i8.Password? password}) =>
      (super.noSuchMethod(
              Invocation.method(#signInWithEmailAndPassword, [],
                  {#emailAddress: emailAddress, #password: password}),
              returnValue: Future<_i2.Either<_i7.AuthFailure, _i2.Unit>>.value(
                  _FakeEither_1<_i7.AuthFailure, _i2.Unit>()))
          as _i6.Future<_i2.Either<_i7.AuthFailure, _i2.Unit>>);
  @override
  _i6.Future<_i2.Either<_i7.AuthFailure, _i2.Unit>> signInWithGoogle() =>
      (super.noSuchMethod(Invocation.method(#signInWithGoogle, []),
              returnValue: Future<_i2.Either<_i7.AuthFailure, _i2.Unit>>.value(
                  _FakeEither_1<_i7.AuthFailure, _i2.Unit>()))
          as _i6.Future<_i2.Either<_i7.AuthFailure, _i2.Unit>>);
  @override
  _i6.Future<void> signOut() =>
      (super.noSuchMethod(Invocation.method(#signOut, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
}

/// A class which mocks [ShopifyUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockShopifyUser extends _i1.Mock implements _i4.ShopifyUser {
  MockShopifyUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.UniqueId get id => (super.noSuchMethod(Invocation.getter(#id),
      returnValue: _FakeUniqueId_2()) as _i3.UniqueId);
  @override
  _i4.$ShopifyUserCopyWith<_i4.ShopifyUser> get copyWith =>
      (super.noSuchMethod(Invocation.getter(#copyWith),
              returnValue: _Fake$ShopifyUserCopyWith_3<_i4.ShopifyUser>())
          as _i4.$ShopifyUserCopyWith<_i4.ShopifyUser>);
  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(Invocation.method(#toJson, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
}
