// Mocks generated by Mockito 5.2.0 from annotations
// in shopify_client/test/application/order_watcher/order_watcher_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:dartz/dartz.dart' as _i4;
import 'package:kt_dart/collection.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shopify_client/domain/order/i_order_facade.dart' as _i2;
import 'package:shopify_domain/order/order.dart' as _i7;
import 'package:shopify_domain/order/order_failure.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [IOrderFacade].
///
/// See the documentation for Mockito's code generation for more information.
class MockIOrderFacade extends _i1.Mock implements _i2.IOrderFacade {
  MockIOrderFacade() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.Either<_i5.OrderFailure, _i6.KtList<_i7.ShopifyOrder>>>
      watchYourOrders(_i7.OrderStatus? status) => (super.noSuchMethod(
          Invocation.method(#watchYourOrders, [status]),
          returnValue: Stream<
              _i4.Either<_i5.OrderFailure,
                  _i6.KtList<_i7.ShopifyOrder>>>.empty()) as _i3
          .Stream<_i4.Either<_i5.OrderFailure, _i6.KtList<_i7.ShopifyOrder>>>);
}
