name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
        working-directory: ./shopify_client
      - run: flutter analyze --no-fatal-infos --no-fatal-warnings
        working-directory: ./shopify_client
      - run: flutter test
        working-directory: ./shopify_client